// ============================================================================
// lang.js — centralized language object.
// Every UI string in the app is read from LANG, never hardcoded elsewhere.
// To translate the app later, this is the only file that needs to change.
// ============================================================================

const LANG = {
  meta: {
    htmlLang: 'en',
    pageTitle: 'Ask UK Intake — September 2026 University Finder',
  },

  brand: 'Ask UK Intake',
  tagline: 'September 2026 · 44 Universities · 4,000+ Courses',

  hero: {
    title: 'Ask about any course, entry criteria, or fee.',
    subtitle: 'Every answer is generated by an AI layer that is grounded strictly in the university intake data below — it never guesses.',
  },

  input: {
    placeholder: 'e.g. What are the entry criteria for Computer Science at York St John?',
    submitAria: 'Ask',
  },

  status: {
    loading: 'Loading university data…',
    ready: (courses, unis) => `${courses.toLocaleString()} courses · ${unis} universities ready`,
    thinking: 'Thinking…',
  },

  browse: {
    show: 'Show full list',
    hide: 'Back to chat',
    levelAll: 'All Levels',
    uniAll: 'All Universities',
    campusAll: 'All Campus',
    empty: 'No results found — try changing the filters.',
  },

  answer: {
    aiLabel: 'AI Answer',
    aiGroundedNote: 'Generated from the matched course/university data below.',
    otherMatches: 'Other possible matches',
    criteriaCategoryMatched: 'Criteria category matched',
    at: 'at',
    detailMissing: 'Detailed criteria could not be extracted for this course yet — please check with the university directly.',
    specificMissing: 'That specific detail could not be extracted — here are the general details instead.',
    noMatchLead: (q) => `No matching course or university was found for "${q}".`,
    noMatchHint: 'Try a different course name or university — for example "Computer Science" or "Middlesex".',
  },

  examples: [
    'Entry criteria for Computer Science at York St John',
    'What is the tuition fee at Middlesex University?',
    'Can I apply to Northumbria without IELTS?',
    'Which universities offer Business Management?',
    'How much scholarship does Arden University give?',
  ],
};

// Expose for both the browser (app.js) and Node (api/chat.js) if ever needed.
if (typeof module !== 'undefined' && module.exports) {
  module.exports = LANG;
}
